apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor-fastapi
  template:
    metadata:
      labels:
        app: order-processor-fastapi
    spec:
      containers:
      - name: order-processor-fastapi
        image: order-processor-fastapi:latest
        ports:
        - containerPort: 5005

---

apiVersion: v1
kind: Service
metadata:
  name: order-processor-fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: order-processor-fastapi
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005

