apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-redux-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-redux-ui
  template:
    metadata:
      labels:
        app: react-redux-ui
    spec:
      containers:
      - name: react-redux-ui
        image: react-redux-ui:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: react-redux-ui-service
spec:
  type: LoadBalancer
  selector:
    app: react-redux-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

