apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor-node
  template:
    metadata:
      labels:
        app: order-processor-node
    spec:
      containers:
      - name: order-processor-node
        image: order-processor-node:latest
        ports:
        - containerPort: 5003

---

apiVersion: v1
kind: Service
metadata:
  name: order-processor-node-service
spec:
  type: LoadBalancer
  selector:
    app: order-processor-node
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
